name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: swiftwasm/swiftwasm-action@v5.3
        with:
          shell-action: swift build --triple wasm32-unknown-wasi
